### PR TITLE
Add contributors section in README file

### PR DESCRIPTION
**Pull request by pedrohyvo**
Just added contributors section in our README.md

### CODE REVIEW

**Comment by pedrohyvo** [comment]
@jaygarcia can you review this PR, please?

**Review by michaeltintiuc — COMMENTED** [review]
Would it be possible to set a single size for all of the avatars?

**Comment by pedrohyvo** [comment]
> Would it be possible to set a single size for all of the avatars?

@michaeltintiuc I was trying to do this, but we have different names size and the image is responsible to fit all screens 🤷‍♂️ but if you have any suggestion how to solve this, I can try

**Comment by michaeltintiuc** [comment]
> > Would it be possible to set a single size for all of the avatars?
> 
> @michaeltintiuc I was trying to do this, but we have different names size and the image is responsible to fit all screens  but if you have any suggestion how to solve this, I can try

Oh NVM, On my phone in the github app it was showing with CSS stripped-down, looks awesome on desktop!

**Review by michaeltintiuc — APPROVED** [review]

**Pull request merged**
